/**
 * Report Decision Node - Decides whether to generate a report and executes generation
 */

import type { GeoAIStateType } from '../GeoAIGraph';
import { ReportGenerator } from '../ReportGenerator';
import type { LLMConfig } from '../../adapters/LLMAdapterFactory';
import fs from 'fs';
import path from 'path';

export interface ReportDecisionNodeConfig {
  llmConfig: LLMConfig;
  workspaceBase: string;
  onPartialResult?: (service: any) => void; // Callback for streaming partial results
  onToken?: (token: string) => void; // Callback for real-time token streaming
}

/**
 * Report Decision Node Function
 * Checks if a report should be generated based on results and user intent.
 */
export async function reportDecisionNode(
  state: GeoAIStateType, 
  config: ReportDecisionNodeConfig
): Promise<Partial<GeoAIStateType>> {
  console.log('[ReportDecisionNode] Evaluating need for report generation...');

  const { llmConfig, workspaceBase } = config;

  // 1. Decision Logic: Check if there are successful results or explicit user request
  const hasResults = state.executionResults && Array.from(state.executionResults.values()).some((r: any) => r.status === 'success');
  const userAskedForReport = state.userInput.toLowerCase().includes('report') || state.userInput.includes('报告');

  if (!hasResults && !userAskedForReport) {
    console.log('[ReportDecisionNode] No results found and no explicit request. Skipping report.');
    return {};
  }

  try {
    // 2. Initialize Generator
    const generator = new ReportGenerator(workspaceBase, llmConfig);
    
    // 3. Prepare Parameters - Aggregate all results from the workflow
    const resultsArray = state.executionResults ? Array.from(state.executionResults.values()) : [];
    const services = state.visualizationServices || [];
    
    console.log(`[ReportDecisionNode] Found ${resultsArray.length} execution results`);
    if (resultsArray.length > 0) {
      console.log('[ReportDecisionNode] First result structure:', JSON.stringify(resultsArray[0], null, 2).substring(0, 500));
    }
    
    // Extract a meaningful title from the first goal or user input
    const goalTitle = state.goals?.[0]?.description || state.userInput;
    
    // 4. Generate Content
    const markdownContent = await generator.generate({
      title: `Analysis Report: ${goalTitle.substring(0, 50)}`,
      summary: state.summary || 'Automated analysis report generated by GeoAI-UP.',
      results: resultsArray,
      services,
      onToken: config.onToken
    });

    // 5. Save to File
    const reportsDir = path.join(workspaceBase, 'results', 'reports');
    if (!fs.existsSync(reportsDir)) {
      fs.mkdirSync(reportsDir, { recursive: true });
    }

    const reportId = `report_${Date.now()}`;
    const fileName = `${reportId}.md`;
    const filePath = path.join(reportsDir, fileName);
    fs.writeFileSync(filePath, markdownContent, 'utf-8');

    console.log(`[ReportDecisionNode] Report saved to: ${filePath}`);

    // 6. Create Service Object
    const reportService = {
      id: `service_${reportId}`,
      type: 'report' as const,
      url: `/api/results/reports/${fileName}`,
      ttl: 3600000,
      expiresAt: new Date(Date.now() + 3600000),
      metadata: {
        title: goalTitle,
        format: 'markdown',
        filePath,
        publicUrl: `/api/results/reports/${fileName}`,
        fileSize: Buffer.byteLength(markdownContent, 'utf-8'),
        generatedAt: new Date().toISOString()
      }
    };

    // 7. Stream the service to frontend if callback is provided
    if (config.onPartialResult) {
      console.log(`[ReportDecisionNode] Streaming report service: ${reportService.id}`);
      config.onPartialResult(reportService);
    }

    return {
      visualizationServices: [...(state.visualizationServices || []), reportService]
    };

  } catch (error) {
    console.error('[ReportDecisionNode] Report generation failed:', error);
    // Don't fail the whole workflow, just skip the report
    return {};
  }
}
